locale: en-US
site_theme: default
title: Junteng Liu
name: Junteng Liu
description: Junteng Liu's academic homepage, researching natural language processing and machine learning at HKUST.
url: https://billkre79.github.io
baseurl: /LJT-Homepage
repository: billkre79/LJT-Homepage
author:
  name: Junteng Liu
  avatar: https://github.com/Vicent0205.png
  bio: Ph.D. student in Computer Science, HKUST NLP Group.
  employer: Hong Kong University of Science and Technology
  email: jliugi@connect.ust.hk
  github: Vicent0205
  twitter: junteng88716710
  googlescholar: https://scholar.google.com/citations?user=tbK9jl4AAAAJ
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, LICENSE, node_modules, vendor, .github, _posts, _talks, _teaching, _portfolio, _publications, markdown_generator, talkmap, files, _pages/cv-json.md, _pages/markdown.md, _pages/portfolio.html, _pages/talks.html, _pages/teaching.html, _pages/talkmap.html, _pages/archive-layout-with-content.md, _pages/non-menu-page.md]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: compressed
plugins: [jekyll-feed, jekyll-gist, jekyll-paginate, jekyll-sitemap, jekyll-redirect-from, jemoji]
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
atom_feed:
  hide: true
comments:
  provider: false
analytics:
  provider: false
words_per_minute: 160
read_more: disabled
permalink: /:categories/:title/
timezone: Etc/UTC
